// juegos.js
window.JUEGOS_CONFIG = {
    "50": "BINGO 50",
    "72": "BINGO 72",
    "90": "BINGO 90",
	"100": "BINGO 100",
    "inv": "INVERTIDOS",
	"bingocartones": "Bingo De Cartones",
    "terna": "TERNAS",
	"mex": "LOTERIA MEXICANA",
	"pokemon": "Pokemon",
	"romanos90": "ROMANOS 90",
    "pais": "PAÍS",
	"power": "LOTERIA DE POWER",
	"novelas": "LOTERIA NOVELAS",
	"fiesta": "LOTERIA FIESTA",
    "bebida": "BEBIDAS",
	"comidas": "COMIDAS",
	"abcdario": "ABCDARIO",
	"comiveneca": "GOURMET VENEZOLANO",
    "pitufo": "PITUFOS",
    "simpson": "LOS SIMPSONS",
	"autos": "AUTOS MARCAS",
	"bomba": "BOMBA",
	"eliminatorias": "ELIMINATORIAS",
	"killernum": "KILLER NUMEROS",
	"killer": "KILLER LETRAS",
	"sumarversus": "SUMATORIA VERSUS",
	"parejasuma": "SUMATORIA PAREJAS",
	"sumaindi": "SUMATORIA INDIVIDUAL",
    "nuevo": "NUEVO JUEGO"
};

window.SORTEADORES_CONFIG = {
    "bingo50": "BINGO 50",
    "bingo72": "BINGO 72",
    "bingo90": "BINGO 90",
	"bingo100": "BINGO 100",
	"bingo120": "TERNA 120",
	"bingocartones": "Bingo De Cartones",
	"romanos90": "ROMANOS 90",
    "paises": "LOTERIA PAÍSES",
    "lm": "LOTERÍA MEXICANA",
	"pokemon": "Pokemon",
	"power": "LOTERIA POWER",
	"novelas": "LOTERIA NOVELAS",
	"fiesta": "LOTERIA FIESTA",
	"simpsons": "LOS SIMPSONS",
    "bebidas": "LOTERÍA BEBIDAS",
	"comidas": "LOTERÍA COMIDAS",
	"comiveneca": "GOURMET VENEZOLANO",
    "pitufos": "LOTERÍA PITUFOS",
	"abcdario": "ABCDARIO",
	"autos": "LOTERIA AUTOS",
	"panel6chat": "6 SALAS CHAT",
	"panelchat": "8 SALAS CHAT"
};